# Generated by Django 4.1.2 on 2022-10-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='user_avatar',
            field=models.ImageField(blank=True, default='no_pic.jpg', upload_to='users_avaters'),
        ),
    ]
