# Generated by Django 4.1.2 on 2022-10-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todouser_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='Task',
        ),
        migrations.AlterField(
            model_name='todouser',
            name='user_avatar',
            field=models.ImageField(blank=True, default='no_pic.jpg', upload_to='users_avater'),
        ),
    ]
